# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true